[waypoints]

# Waypoints marking the end of each segment, in order, and the distance in km each is
# into the course. The last entry is the finish line and there is no entry for the
# starting line.
#
# After changing these, run `plot_segments.py` to see how well constant-grade segments
# split at these waypoints approximate the grade of the course, and to confirm that the
# gates marking the end of each segment don't overlap the course too early (e.g. if
# there are switchback sections), which would trigger end-of-segment detection
# prematurely

"Trestle Bridge Bend" = 1.200
"Selby" = 2.500
"Aura Rd Crossing" = 3.260
"Old Menzies Ck Rd" = 5.025
"Menzies Ck Crossing" = 6.590
"Menzies Rd Crest" = 7.340
"Clematis Crossing" = 7.830
"Clematis Pub" = 8.700
"Emerald Crossing" = 10.260
"Lakeside" = 13.613


[pacing]

# The target pace for each segment, either given as an explicit list or calculated from
# a flat pace and a split delta, with each segment grade-adjusted using Strava's
# grade-adjusted pace (GAP) curve. If the explicit list is present, the remaining
# configuration in this section is ignored

# paces = [
#     "4:27", "5:50", "4:46", "4:33", "6:12",
#     "5:16", "4:03", "4:44", "5:30", "4:34",
# ]

# The average pace you would run the course at if it were flat
flat_pace = "4:50"

# The fractional difference in pace between the second and first half of an equivalent
# flat course with a linear ramp in pace, i.e. -0.01 is what is usually referred to as a
# "1% negative split"
split_delta = -0.01


[tracking]

# Other config parameters used on the watch 

# How much further in metres one can run in a segment, in excess of the expected length
# of the segment, before the field advances to the next segment despite not having
# encountered the end-of-segment waypoint
overdistance = 200

# Averaging length scale in metres for the performance ratio - how fast one is running
# as a fraction of target, used for one of the finishing time projections
perf_ratio_scale = 250
